"""Video game development module — scaffold, manage, and build games.

Provides the AI agent with game development capabilities:

1. **Project scaffolding** — generate starter projects for popular
   frameworks (Pygame, Godot, Phaser/JS, Unity C#, Love2D).
2. **GitHub integration** — clone game repos, fork templates, and
   manage game project repos.
3. **Asset generation** — create placeholder sprites, tilemaps, and
   config files via code.
4. **Game templates** — ready-to-run templates for common genres
   (platformer, top-down RPG, puzzle, space shooter, etc.).
5. **Build helpers** — package games for distribution.

No heavy dependencies — generates source files the user can run with
their chosen engine/framework.
"""

from __future__ import annotations

import json
import os
import subprocess
import time
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_PROJECTS_DIR = os.path.join(os.path.dirname(__file__), "game_projects")
_REGISTRY_FILE = os.path.join(_DATA_DIR, "game_registry.json")


# ---------------------------------------------------------------------------
# Framework definitions
# ---------------------------------------------------------------------------

FRAMEWORKS: dict[str, dict[str, Any]] = {
    "pygame": {
        "name": "Pygame",
        "language": "Python",
        "description": "2D game framework for Python. Great for beginners.",
        "install": "pip install pygame",
        "run": "python main.py",
        "file_ext": ".py",
        "website": "https://www.pygame.org",
    },
    "godot": {
        "name": "Godot (GDScript)",
        "language": "GDScript",
        "description": "Open-source 2D/3D game engine with its own scripting language.",
        "install": "Download from https://godotengine.org/download",
        "run": "Open project.godot in Godot Editor",
        "file_ext": ".gd",
        "website": "https://godotengine.org",
    },
    "phaser": {
        "name": "Phaser 3",
        "language": "JavaScript",
        "description": "HTML5 2D game framework. Games run in the browser.",
        "install": "npm install phaser  (or use CDN)",
        "run": "Open index.html in browser (or use a local server)",
        "file_ext": ".js",
        "website": "https://phaser.io",
    },
    "love2d": {
        "name": "Love2D",
        "language": "Lua",
        "description": "Simple 2D game framework for Lua. Very beginner-friendly.",
        "install": "Download from https://love2d.org",
        "run": "love .",
        "file_ext": ".lua",
        "website": "https://love2d.org",
    },
    "unity": {
        "name": "Unity (C#)",
        "language": "C#",
        "description": "Industry-standard 2D/3D game engine.",
        "install": "Download Unity Hub from https://unity.com/download",
        "run": "Open folder in Unity Editor",
        "file_ext": ".cs",
        "website": "https://unity.com",
    },
}

# ---------------------------------------------------------------------------
# Genre templates
# ---------------------------------------------------------------------------

GENRES: dict[str, dict[str, str]] = {
    "platformer": {
        "name": "2D Platformer",
        "description": "Side-scrolling platformer with jump mechanics, platforms, and enemies.",
    },
    "topdown_rpg": {
        "name": "Top-Down RPG",
        "description": "Top-down RPG with tile-based movement, NPCs, and dialogue.",
    },
    "space_shooter": {
        "name": "Space Shooter",
        "description": "Vertical scrolling space shooter with enemies and powerups.",
    },
    "puzzle": {
        "name": "Puzzle Game",
        "description": "Grid-based puzzle game (match-3, sokoban, etc.).",
    },
    "endless_runner": {
        "name": "Endless Runner",
        "description": "Auto-scrolling runner with obstacles and score tracking.",
    },
}


# ---------------------------------------------------------------------------
# Pygame template generators
# ---------------------------------------------------------------------------

def _pygame_platformer(name: str) -> dict[str, str]:
    """Generate a Pygame platformer project."""
    return {
        "main.py": f'''"""
{name} — 2D Platformer
Generated by Cornerstone AI Game Dev Module
"""
import pygame
import sys

# --- Constants ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
GRAVITY = 0.8
JUMP_FORCE = -15
PLAYER_SPEED = 5

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (50, 120, 200)
GREEN = (50, 180, 50)
RED = (200, 50, 50)

class Player(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = pygame.Surface((32, 48))
        self.image.fill(BLUE)
        self.rect = self.image.get_rect(topleft=(x, y))
        self.vel_y = 0
        self.on_ground = False
        self.score = 0

    def update(self, platforms):
        keys = pygame.key.get_pressed()
        dx = 0
        if keys[pygame.K_LEFT] or keys[pygame.K_a]:
            dx = -PLAYER_SPEED
        if keys[pygame.K_RIGHT] or keys[pygame.K_d]:
            dx = PLAYER_SPEED
        if (keys[pygame.K_SPACE] or keys[pygame.K_UP]) and self.on_ground:
            self.vel_y = JUMP_FORCE
            self.on_ground = False

        self.vel_y += GRAVITY
        self.rect.x += dx
        self.rect.y += int(self.vel_y)

        # Platform collision
        self.on_ground = False
        for plat in platforms:
            if self.rect.colliderect(plat.rect):
                if self.vel_y > 0:
                    self.rect.bottom = plat.rect.top
                    self.vel_y = 0
                    self.on_ground = True

        # Screen bounds
        if self.rect.left < 0:
            self.rect.left = 0
        if self.rect.right > SCREEN_WIDTH:
            self.rect.right = SCREEN_WIDTH
        if self.rect.top > SCREEN_HEIGHT:
            self.rect.y = 0  # respawn at top

class Platform(pygame.sprite.Sprite):
    def __init__(self, x, y, w, h):
        super().__init__()
        self.image = pygame.Surface((w, h))
        self.image.fill(GREEN)
        self.rect = self.image.get_rect(topleft=(x, y))

class Coin(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = pygame.Surface((16, 16))
        pygame.draw.circle(self.image, (255, 215, 0), (8, 8), 8)
        self.image.set_colorkey(BLACK)
        self.rect = self.image.get_rect(center=(x, y))

def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption("{name}")
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 36)

    player = Player(100, 400)
    platforms = pygame.sprite.Group()
    coins = pygame.sprite.Group()
    all_sprites = pygame.sprite.Group()

    # Ground
    platforms.add(Platform(0, 550, 800, 50))
    # Platforms
    for i, (x, y, w) in enumerate([
        (150, 450, 120), (350, 380, 100), (550, 300, 130),
        (200, 220, 110), (450, 150, 100), (100, 100, 80),
    ]):
        p = Platform(x, y, w, 20)
        platforms.add(p)
        c = Coin(x + w // 2, y - 20)
        coins.add(c)

    all_sprites.add(player)
    all_sprites.add(*platforms)
    all_sprites.add(*coins)

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                running = False

        player.update(platforms)
        collected = pygame.sprite.spritecollide(player, coins, True)
        player.score += len(collected)

        screen.fill(BLACK)
        all_sprites.draw(screen)
        score_text = font.render(f"Score: {{player.score}}", True, WHITE)
        screen.blit(score_text, (10, 10))
        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
''',
        "README.md": f"# {name}\n\nA 2D platformer built with Pygame.\n\n"
        f"## Run\n```\npip install pygame\npython main.py\n```\n\n"
        f"## Controls\n- Arrow keys / WASD: Move\n- Space: Jump\n- Esc: Quit\n",
        "requirements.txt": "pygame>=2.5.0\n",
    }


def _pygame_space_shooter(name: str) -> dict[str, str]:
    """Generate a Pygame space shooter project."""
    return {
        "main.py": f'''"""
{name} — Space Shooter
Generated by Cornerstone AI Game Dev Module
"""
import pygame
import sys
import random

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800
FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 50, 50)
YELLOW = (255, 255, 0)
CYAN = (0, 255, 255)

class Player(pygame.sprite.Sprite):
    def __init__(self):
        super().__init__()
        self.image = pygame.Surface((40, 40), pygame.SRCALPHA)
        pygame.draw.polygon(self.image, CYAN, [(20, 0), (0, 40), (40, 40)])
        self.rect = self.image.get_rect(center=(SCREEN_WIDTH // 2, 700))
        self.speed = 6
        self.shoot_delay = 200
        self.last_shot = 0

    def update(self):
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT] and self.rect.left > 0:
            self.rect.x -= self.speed
        if keys[pygame.K_RIGHT] and self.rect.right < SCREEN_WIDTH:
            self.rect.x += self.speed

    def shoot(self):
        now = pygame.time.get_ticks()
        if now - self.last_shot > self.shoot_delay:
            self.last_shot = now
            return Bullet(self.rect.centerx, self.rect.top)
        return None

class Bullet(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = pygame.Surface((4, 12))
        self.image.fill(YELLOW)
        self.rect = self.image.get_rect(center=(x, y))
        self.speed = -10

    def update(self):
        self.rect.y += self.speed
        if self.rect.bottom < 0:
            self.kill()

class Enemy(pygame.sprite.Sprite):
    def __init__(self):
        super().__init__()
        self.image = pygame.Surface((30, 30))
        self.image.fill(RED)
        self.rect = self.image.get_rect(
            center=(random.randint(30, SCREEN_WIDTH - 30), -30)
        )
        self.speed = random.uniform(2, 5)

    def update(self):
        self.rect.y += self.speed
        if self.rect.top > SCREEN_HEIGHT:
            self.kill()

def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption("{name}")
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 36)

    player = Player()
    bullets = pygame.sprite.Group()
    enemies = pygame.sprite.Group()
    all_sprites = pygame.sprite.Group(player)

    score = 0
    enemy_timer = 0

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                running = False

        keys = pygame.key.get_pressed()
        player.update()

        if keys[pygame.K_SPACE]:
            bullet = player.shoot()
            if bullet:
                bullets.add(bullet)
                all_sprites.add(bullet)

        enemy_timer += 1
        if enemy_timer > 30:
            enemy_timer = 0
            e = Enemy()
            enemies.add(e)
            all_sprites.add(e)

        bullets.update()
        enemies.update()

        hits = pygame.sprite.groupcollide(enemies, bullets, True, True)
        score += len(hits)

        if pygame.sprite.spritecollideany(player, enemies):
            running = False  # Game over

        screen.fill(BLACK)
        # Stars
        for _ in range(2):
            x = random.randint(0, SCREEN_WIDTH)
            y = random.randint(0, SCREEN_HEIGHT)
            screen.set_at((x, y), WHITE)
        all_sprites.draw(screen)
        score_text = font.render(f"Score: {{score}}", True, WHITE)
        screen.blit(score_text, (10, 10))
        pygame.display.flip()
        clock.tick(FPS)

    # Game over screen
    over_text = font.render(f"GAME OVER — Score: {{score}}", True, RED)
    screen.blit(over_text, (SCREEN_WIDTH // 2 - 150, SCREEN_HEIGHT // 2))
    pygame.display.flip()
    pygame.time.wait(2000)
    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
''',
        "README.md": f"# {name}\n\nA space shooter built with Pygame.\n\n"
        f"## Run\n```\npip install pygame\npython main.py\n```\n\n"
        f"## Controls\n- Arrow keys: Move\n- Space: Shoot\n- Esc: Quit\n",
        "requirements.txt": "pygame>=2.5.0\n",
    }


def _pygame_puzzle(name: str) -> dict[str, str]:
    """Generate a Pygame match-3 puzzle game."""
    return {
        "main.py": f'''"""
{name} — Puzzle Game (Sokoban-style)
Generated by Cornerstone AI Game Dev Module
"""
import pygame
import sys

TILE = 48
COLS, ROWS = 10, 10
SCREEN_WIDTH = COLS * TILE
SCREEN_HEIGHT = ROWS * TILE + 60
FPS = 30

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (100, 100, 100)
BLUE = (50, 100, 200)
BROWN = (139, 90, 43)
GREEN = (50, 200, 50)
RED = (200, 50, 50)
YELLOW = (255, 215, 0)

# Level: W=wall, P=player, B=box, T=target, .=floor
LEVEL = [
    "WWWWWWWWWW",
    "W........W",
    "W..B.....W",
    "W........W",
    "W....T...W",
    "W........W",
    "W..B.T...W",
    "W........W",
    "W.P......W",
    "WWWWWWWWWW",
]

def parse_level(level):
    walls, boxes, targets = [], [], []
    player = (0, 0)
    for r, row in enumerate(level):
        for c, ch in enumerate(row):
            if ch == "W":
                walls.append((c, r))
            elif ch == "P":
                player = (c, r)
            elif ch == "B":
                boxes.append((c, r))
            elif ch == "T":
                targets.append((c, r))
    return player, walls, boxes, targets

def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption("{name}")
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 32)

    player, walls, boxes, targets = parse_level(LEVEL)
    moves = 0

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                dx, dy = 0, 0
                if event.key in (pygame.K_LEFT, pygame.K_a): dx = -1
                if event.key in (pygame.K_RIGHT, pygame.K_d): dx = 1
                if event.key in (pygame.K_UP, pygame.K_w): dy = -1
                if event.key in (pygame.K_DOWN, pygame.K_s): dy = 1
                if event.key == pygame.K_r:
                    player, walls, boxes, targets = parse_level(LEVEL)
                    moves = 0
                    continue

                if dx or dy:
                    nx, ny = player[0] + dx, player[1] + dy
                    if (nx, ny) not in walls:
                        if (nx, ny) in boxes:
                            bx, by = nx + dx, ny + dy
                            if (bx, by) not in walls and (bx, by) not in boxes:
                                boxes.remove((nx, ny))
                                boxes.append((bx, by))
                                player = (nx, ny)
                                moves += 1
                        else:
                            player = (nx, ny)
                            moves += 1

        screen.fill(BLACK)
        for (x, y) in walls:
            pygame.draw.rect(screen, GRAY, (x*TILE, y*TILE, TILE, TILE))
        for (x, y) in targets:
            pygame.draw.circle(screen, GREEN, (x*TILE+TILE//2, y*TILE+TILE//2), 8)
        for (x, y) in boxes:
            color = YELLOW if (x, y) in targets else BROWN
            pygame.draw.rect(screen, color, (x*TILE+4, y*TILE+4, TILE-8, TILE-8))
        px, py = player
        pygame.draw.rect(screen, BLUE, (px*TILE+6, py*TILE+6, TILE-12, TILE-12))

        won = all(b in targets for b in boxes)
        status = "YOU WIN!" if won else f"Moves: {{moves}}  (R=restart)"
        text = font.render(status, True, WHITE)
        screen.blit(text, (10, SCREEN_HEIGHT - 40))
        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
''',
        "README.md": f"# {name}\n\nA Sokoban-style puzzle game built with Pygame.\n\n"
        f"## Run\n```\npip install pygame\npython main.py\n```\n\n"
        f"## Controls\n- Arrow keys / WASD: Move\n- R: Restart level\n- Esc: Quit\n"
        f"\n## Goal\nPush all boxes onto the green targets.\n",
        "requirements.txt": "pygame>=2.5.0\n",
    }


def _pygame_topdown_rpg(name: str) -> dict[str, str]:
    """Generate a Pygame top-down RPG project."""
    return {
        "main.py": f'''"""
{name} — Top-Down RPG
Generated by Cornerstone AI Game Dev Module
"""
import pygame
import sys

TILE = 32
MAP_W, MAP_H = 20, 15
SCREEN_WIDTH = MAP_W * TILE
SCREEN_HEIGHT = MAP_H * TILE + 80
FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (34, 120, 34)
DARK_GREEN = (20, 80, 20)
BROWN = (139, 90, 43)
BLUE = (50, 100, 220)
RED = (200, 50, 50)
GRAY = (100, 100, 100)
YELLOW = (255, 215, 0)

class Player:
    def __init__(self, x, y):
        self.x, self.y = x, y
        self.hp = 100
        self.max_hp = 100
        self.attack = 10
        self.speed = 3
        self.xp = 0
        self.level = 1

    def draw(self, screen):
        pygame.draw.rect(screen, BLUE, (self.x, self.y, TILE-4, TILE-4))
        # HP bar
        bar_w = TILE - 4
        hp_w = int(bar_w * self.hp / self.max_hp)
        pygame.draw.rect(screen, RED, (self.x, self.y - 6, bar_w, 4))
        pygame.draw.rect(screen, GREEN, (self.x, self.y - 6, hp_w, 4))

class NPC:
    def __init__(self, x, y, dialogue):
        self.x, self.y = x, y
        self.dialogue = dialogue
        self.talked = False

    def draw(self, screen):
        pygame.draw.rect(screen, YELLOW, (self.x, self.y, TILE-4, TILE-4))
        if not self.talked:
            pygame.draw.circle(screen, WHITE, (self.x + TILE//2, self.y - 8), 4)

class Enemy:
    def __init__(self, x, y, hp=30):
        self.x, self.y = x, y
        self.hp = hp
        self.max_hp = hp
        self.alive = True

    def draw(self, screen):
        if not self.alive:
            return
        pygame.draw.rect(screen, RED, (self.x, self.y, TILE-4, TILE-4))
        bar_w = TILE - 4
        hp_w = int(bar_w * self.hp / self.max_hp)
        pygame.draw.rect(screen, RED, (self.x, self.y - 6, bar_w, 4))
        pygame.draw.rect(screen, GREEN, (self.x, self.y - 6, hp_w, 4))

def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption("{name}")
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 24)

    player = Player(5 * TILE, 7 * TILE)
    npcs = [
        NPC(8 * TILE, 4 * TILE, "Welcome to the village! Watch out for slimes."),
        NPC(14 * TILE, 10 * TILE, "The treasure is hidden in the east."),
    ]
    enemies = [
        Enemy(12 * TILE, 6 * TILE),
        Enemy(16 * TILE, 3 * TILE),
        Enemy(18 * TILE, 12 * TILE, hp=50),
    ]
    walls = [(0, y) for y in range(MAP_H)] + [(MAP_W-1, y) for y in range(MAP_H)]
    walls += [(x, 0) for x in range(MAP_W)] + [(x, MAP_H-1) for x in range(MAP_W)]
    walls += [(6, y) for y in range(3, 8)] + [(10, y) for y in range(8, 13)]

    message = "Arrow keys to move, E to interact, Space to attack"
    msg_timer = 180

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                if event.key == pygame.K_e:
                    for npc in npcs:
                        dist = abs(player.x - npc.x) + abs(player.y - npc.y)
                        if dist < TILE * 2:
                            message = npc.dialogue
                            msg_timer = 180
                            npc.talked = True
                if event.key == pygame.K_SPACE:
                    for enemy in enemies:
                        if not enemy.alive:
                            continue
                        dist = abs(player.x - enemy.x) + abs(player.y - enemy.y)
                        if dist < TILE * 2:
                            enemy.hp -= player.attack
                            if enemy.hp <= 0:
                                enemy.alive = False
                                player.xp += 25
                                message = f"Enemy defeated! +25 XP"
                                msg_timer = 120
                                if player.xp >= player.level * 50:
                                    player.level += 1
                                    player.attack += 3
                                    player.max_hp += 20
                                    player.hp = player.max_hp
                                    message = f"Level up! Now level {{player.level}}"
                                    msg_timer = 180

        keys = pygame.key.get_pressed()
        dx, dy = 0, 0
        if keys[pygame.K_LEFT]: dx = -player.speed
        if keys[pygame.K_RIGHT]: dx = player.speed
        if keys[pygame.K_UP]: dy = -player.speed
        if keys[pygame.K_DOWN]: dy = player.speed

        nx = player.x + dx
        ny = player.y + dy
        tile_x, tile_y = int(nx // TILE), int(ny // TILE)
        if (tile_x, tile_y) not in walls:
            player.x, player.y = nx, ny

        # Draw
        screen.fill(DARK_GREEN)
        for wx, wy in walls:
            pygame.draw.rect(screen, GRAY, (wx*TILE, wy*TILE, TILE, TILE))
        for npc in npcs:
            npc.draw(screen)
        for enemy in enemies:
            enemy.draw(screen)
        player.draw(screen)

        # HUD
        hud_y = MAP_H * TILE + 5
        pygame.draw.rect(screen, BLACK, (0, MAP_H * TILE, SCREEN_WIDTH, 80))
        hp_text = font.render(f"HP: {{player.hp}}/{{player.max_hp}}", True, GREEN)
        xp_text = font.render(f"Lv.{{player.level}} XP: {{player.xp}}", True, YELLOW)
        atk_text = font.render(f"ATK: {{player.attack}}", True, RED)
        screen.blit(hp_text, (10, hud_y))
        screen.blit(xp_text, (150, hud_y))
        screen.blit(atk_text, (300, hud_y))

        if msg_timer > 0:
            msg_surf = font.render(message, True, WHITE)
            screen.blit(msg_surf, (10, hud_y + 30))
            msg_timer -= 1

        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
''',
        "README.md": f"# {name}\n\nA top-down RPG built with Pygame.\n\n"
        f"## Run\n```\npip install pygame\npython main.py\n```\n\n"
        f"## Controls\n- Arrow keys: Move\n- E: Talk to NPCs\n"
        f"- Space: Attack\n- Esc: Quit\n",
        "requirements.txt": "pygame>=2.5.0\n",
    }


def _pygame_endless_runner(name: str) -> dict[str, str]:
    """Generate a Pygame endless runner project."""
    return {
        "main.py": f'''"""
{name} — Endless Runner
Generated by Cornerstone AI Game Dev Module
"""
import pygame
import sys
import random

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
FPS = 60
GROUND_Y = 320

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
SKY = (135, 206, 235)
GREEN = (34, 139, 34)
RED = (200, 50, 50)
GRAY = (100, 100, 100)

class Runner(pygame.sprite.Sprite):
    def __init__(self):
        super().__init__()
        self.image = pygame.Surface((30, 50))
        self.image.fill((50, 100, 220))
        self.rect = self.image.get_rect(bottomleft=(80, GROUND_Y))
        self.vel_y = 0
        self.jumping = False
        self.ducking = False

    def jump(self):
        if not self.jumping:
            self.vel_y = -16
            self.jumping = True

    def duck(self, active):
        self.ducking = active
        if active:
            self.image = pygame.Surface((30, 25))
            self.image.fill((50, 100, 220))
            old_bottom = self.rect.bottom
            self.rect = self.image.get_rect(bottomleft=(self.rect.left, old_bottom))
        else:
            self.image = pygame.Surface((30, 50))
            self.image.fill((50, 100, 220))
            old_bottom = self.rect.bottom
            self.rect = self.image.get_rect(bottomleft=(self.rect.left, old_bottom))

    def update(self):
        self.vel_y += 0.9
        self.rect.y += int(self.vel_y)
        if self.rect.bottom >= GROUND_Y:
            self.rect.bottom = GROUND_Y
            self.vel_y = 0
            self.jumping = False

class Obstacle(pygame.sprite.Sprite):
    def __init__(self, kind="cactus"):
        super().__init__()
        if kind == "cactus":
            w, h = 20, random.choice([40, 55, 70])
            self.image = pygame.Surface((w, h))
            self.image.fill(GREEN)
            self.rect = self.image.get_rect(bottomleft=(SCREEN_WIDTH + 20, GROUND_Y))
        else:
            w, h = 50, 20
            self.image = pygame.Surface((w, h))
            self.image.fill(GRAY)
            self.rect = self.image.get_rect(bottomleft=(SCREEN_WIDTH + 20, GROUND_Y - 60))
        self.speed = 7

    def update(self):
        self.rect.x -= self.speed
        if self.rect.right < 0:
            self.kill()

def main():
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption("{name}")
    clock = pygame.time.Clock()
    font = pygame.font.Font(None, 36)

    runner = Runner()
    obstacles = pygame.sprite.Group()
    all_sprites = pygame.sprite.Group(runner)

    score = 0
    spawn_timer = 0
    game_speed = 7

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                if event.key in (pygame.K_SPACE, pygame.K_UP):
                    runner.jump()
                if event.key == pygame.K_DOWN:
                    runner.duck(True)
            if event.type == pygame.KEYUP:
                if event.key == pygame.K_DOWN:
                    runner.duck(False)

        runner.update()
        obstacles.update()
        score += 1

        spawn_timer += 1
        if spawn_timer > random.randint(40, 80):
            spawn_timer = 0
            kind = random.choice(["cactus", "cactus", "bird"])
            obs = Obstacle(kind)
            obs.speed = game_speed
            obstacles.add(obs)
            all_sprites.add(obs)

        if score % 500 == 0:
            game_speed += 0.5

        if pygame.sprite.spritecollideany(runner, obstacles):
            running = False

        screen.fill(SKY)
        pygame.draw.rect(screen, (194, 178, 128), (0, GROUND_Y, SCREEN_WIDTH, 80))
        all_sprites.draw(screen)
        score_text = font.render(f"Score: {{score // 5}}", True, BLACK)
        screen.blit(score_text, (SCREEN_WIDTH - 200, 20))
        pygame.display.flip()
        clock.tick(FPS)

    over_text = font.render(f"GAME OVER — Score: {{score // 5}}", True, RED)
    screen.blit(over_text, (SCREEN_WIDTH // 2 - 150, SCREEN_HEIGHT // 2))
    pygame.display.flip()
    pygame.time.wait(2000)
    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()
''',
        "README.md": f"# {name}\n\nAn endless runner built with Pygame.\n\n"
        f"## Run\n```\npip install pygame\npython main.py\n```\n\n"
        f"## Controls\n- Space / Up: Jump\n- Down: Duck\n- Esc: Quit\n",
        "requirements.txt": "pygame>=2.5.0\n",
    }


# Map framework+genre to generators
_PYGAME_GENERATORS: dict[str, Any] = {
    "platformer": _pygame_platformer,
    "space_shooter": _pygame_space_shooter,
    "puzzle": _pygame_puzzle,
    "topdown_rpg": _pygame_topdown_rpg,
    "endless_runner": _pygame_endless_runner,
}


# ---------------------------------------------------------------------------
# Phaser (HTML5/JS) templates
# ---------------------------------------------------------------------------

def _phaser_platformer(name: str) -> dict[str, str]:
    """Generate a Phaser 3 platformer project."""
    return {
        "index.html": f"""<!DOCTYPE html>
<html>
<head>
    <title>{name}</title>
    <script src="https://cdn.jsdelivr.net/npm/phaser@3.60.0/dist/phaser.min.js"></script>
</head>
<body style="margin:0; background:#000;">
<script src="game.js"></script>
</body>
</html>
""",
        "game.js": f"""// {name} — Phaser 3 Platformer
// Generated by Cornerstone AI Game Dev Module

const config = {{
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    physics: {{
        default: 'arcade',
        arcade: {{ gravity: {{ y: 800 }}, debug: false }}
    }},
    scene: {{ preload, create, update }}
}};

const game = new Phaser.Game(config);
let player, cursors, platforms, coins, scoreText;
let score = 0;

function preload() {{
    // Create colored rectangles as textures
    const g = this.make.graphics({{ add: false }});
    g.fillStyle(0x3366cc); g.fillRect(0, 0, 32, 48);
    g.generateTexture('player', 32, 48);
    g.clear(); g.fillStyle(0x33aa33); g.fillRect(0, 0, 200, 20);
    g.generateTexture('platform', 200, 20);
    g.clear(); g.fillStyle(0x33aa33); g.fillRect(0, 0, 800, 40);
    g.generateTexture('ground', 800, 40);
    g.clear(); g.fillStyle(0xffdd00); g.fillCircle(8, 8, 8);
    g.generateTexture('coin', 16, 16);
    g.destroy();
}}

function create() {{
    platforms = this.physics.add.staticGroup();
    platforms.create(400, 580, 'ground');
    platforms.create(200, 450, 'platform');
    platforms.create(500, 350, 'platform');
    platforms.create(150, 250, 'platform');
    platforms.create(600, 200, 'platform');

    player = this.physics.add.sprite(100, 400, 'player');
    player.setBounce(0.1);
    player.setCollideWorldBounds(true);

    coins = this.physics.add.group();
    [{{x:200,y:400}}, {{x:500,y:300}}, {{x:150,y:200}}, {{x:600,y:150}}].forEach(p => {{
        coins.create(p.x, p.y, 'coin');
    }});

    this.physics.add.collider(player, platforms);
    this.physics.add.collider(coins, platforms);
    this.physics.add.overlap(player, coins, collectCoin, null, this);

    cursors = this.input.keyboard.createCursorKeys();
    scoreText = this.add.text(16, 16, 'Score: 0', {{
        fontSize: '24px', fill: '#fff'
    }});
}}

function update() {{
    if (cursors.left.isDown) {{
        player.setVelocityX(-200);
    }} else if (cursors.right.isDown) {{
        player.setVelocityX(200);
    }} else {{
        player.setVelocityX(0);
    }}
    if (cursors.up.isDown && player.body.touching.down) {{
        player.setVelocityY(-500);
    }}
}}

function collectCoin(player, coin) {{
    coin.disableBody(true, true);
    score += 10;
    scoreText.setText('Score: ' + score);
}}
""",
        "README.md": f"# {name}\n\nA Phaser 3 platformer that runs in the browser.\n\n"
        f"## Run\nOpen `index.html` in your browser, or use a local server:\n"
        f"```\npython -m http.server 8080\n```\nThen open http://localhost:8080\n\n"
        f"## Controls\n- Arrow keys: Move & Jump\n",
    }


_PHASER_GENERATORS: dict[str, Any] = {
    "platformer": _phaser_platformer,
}


# ---------------------------------------------------------------------------
# Tool functions (called by the agent)
# ---------------------------------------------------------------------------

def create_game_project(
    name: str = "",
    framework: str = "pygame",
    genre: str = "platformer",
) -> str:
    """Create a new game project with the specified framework and genre.

    Generates all necessary files in agent_v2/game_projects/<name>/.
    """
    if not name:
        name = f"my_{genre}_game"

    # Sanitize name
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
    project_dir = os.path.join(_PROJECTS_DIR, safe_name)

    if os.path.isdir(project_dir):
        return f"Error: project '{safe_name}' already exists at {project_dir}"

    # Select generator
    files: dict[str, str] = {}

    if framework == "pygame":
        generator = _PYGAME_GENERATORS.get(genre)
        if generator:
            files = generator(name)
        else:
            available = ", ".join(sorted(_PYGAME_GENERATORS.keys()))
            return (
                f"Error: no Pygame template for genre '{genre}'. "
                f"Available: {available}"
            )
    elif framework == "phaser":
        generator = _PHASER_GENERATORS.get(genre)
        if generator:
            files = generator(name)
        else:
            return (
                f"Error: no Phaser template for genre '{genre}'. "
                f"Available: platformer"
            )
    else:
        available_fw = ", ".join(sorted(FRAMEWORKS.keys()))
        return (
            f"Error: no templates for framework '{framework}' yet. "
            f"Available with templates: pygame, phaser. "
            f"All frameworks: {available_fw}"
        )

    # Write files
    os.makedirs(project_dir, exist_ok=True)
    for filename, content in files.items():
        filepath = os.path.join(project_dir, filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(content)

    # Register project
    _register_project(safe_name, framework, genre, project_dir)

    fw_info = FRAMEWORKS.get(framework, {})
    return (
        f"Game project created: {project_dir}\n\n"
        f"Framework: {fw_info.get('name', framework)}\n"
        f"Genre: {GENRES.get(genre, {}).get('name', genre)}\n"
        f"Files: {', '.join(files.keys())}\n\n"
        f"To run:\n"
        f"  1. cd {project_dir}\n"
        f"  2. {fw_info.get('install', '')}\n"
        f"  3. {fw_info.get('run', '')}\n"
    )


def clone_game_repo(repo_url: str, name: str = "") -> str:
    """Clone a game repository from GitHub into the game projects directory."""
    os.makedirs(_PROJECTS_DIR, exist_ok=True)

    if not name:
        # Extract repo name from URL
        name = repo_url.rstrip("/").split("/")[-1]
        if name.endswith(".git"):
            name = name[:-4]

    project_dir = os.path.join(_PROJECTS_DIR, name)
    if os.path.isdir(project_dir):
        return f"Error: directory '{name}' already exists at {project_dir}"

    try:
        result = subprocess.run(
            ["git", "clone", repo_url, project_dir],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            return f"Error cloning repo: {result.stderr}"

        _register_project(name, "custom", "custom", project_dir)
        return (
            f"Repository cloned: {project_dir}\n"
            f"Source: {repo_url}\n\n"
            f"Check the README for setup and run instructions."
        )
    except subprocess.TimeoutExpired:
        return "Error: git clone timed out after 120 seconds."
    except Exception as exc:
        return f"Error: {exc}"


def list_game_projects() -> str:
    """List all game projects."""
    registry = _load_registry()
    if not registry:
        return (
            "No game projects yet. Use create_game_project to start one, "
            "or clone_game_repo to clone from GitHub."
        )

    lines = [f"Game projects ({len(registry)}):\n"]
    for i, proj in enumerate(registry):
        lines.append(
            f"  {i}. {proj.get('name', '?')} "
            f"({proj.get('framework', '?')}/{proj.get('genre', '?')}) — "
            f"{proj.get('path', '?')}"
        )
    return "\n".join(lines)


def list_game_frameworks() -> str:
    """List all supported game frameworks."""
    lines = ["Supported game frameworks:\n"]
    for key, fw in sorted(FRAMEWORKS.items()):
        lines.append(f"  {key}: {fw['name']} ({fw['language']})")
        lines.append(f"    {fw['description']}")
        lines.append(f"    Install: {fw['install']}")
        lines.append(f"    Run: {fw['run']}")
        lines.append(f"    Website: {fw['website']}")
        lines.append("")
    return "\n".join(lines)


def list_game_genres() -> str:
    """List all available game genre templates."""
    lines = ["Available game genres:\n"]
    for key, genre in sorted(GENRES.items()):
        lines.append(f"  {key}: {genre['name']} — {genre['description']}")
    lines.append(
        "\nNote: Not all genre+framework combos have templates. "
        "Pygame has all genres, Phaser has platformer."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Registry persistence
# ---------------------------------------------------------------------------

def _load_registry() -> list[dict[str, Any]]:
    if os.path.isfile(_REGISTRY_FILE):
        try:
            with open(_REGISTRY_FILE, "r", encoding="utf-8") as fh:
                data = json.load(fh)
                return data if isinstance(data, list) else []
        except (json.JSONDecodeError, OSError):
            pass
    return []


def _register_project(
    name: str, framework: str, genre: str, path: str
) -> None:
    registry = _load_registry()
    registry.append({
        "name": name,
        "framework": framework,
        "genre": genre,
        "path": path,
        "created_at": time.time(),
    })
    os.makedirs(_DATA_DIR, exist_ok=True)
    with open(_REGISTRY_FILE, "w", encoding="utf-8") as fh:
        json.dump(registry, fh, indent=2, default=str)


# ---------------------------------------------------------------------------
# Display helpers (for /gamedev command)
# ---------------------------------------------------------------------------

def print_gamedev_status() -> None:
    """Print game development module status."""
    registry = _load_registry()
    table = Table(title="Game Development Module")
    table.add_column("Item", style="bold cyan")
    table.add_column("Value")
    table.add_row("Frameworks", ", ".join(sorted(FRAMEWORKS.keys())))
    table.add_row("Genre templates", ", ".join(sorted(GENRES.keys())))
    table.add_row("Projects created", str(len(registry)))
    table.add_row("Projects directory", _PROJECTS_DIR)
    console.print(table)

    if registry:
        proj_table = Table(title="Game Projects")
        proj_table.add_column("#", style="bold")
        proj_table.add_column("Name")
        proj_table.add_column("Framework", style="cyan")
        proj_table.add_column("Genre")
        proj_table.add_column("Path", style="dim")
        for i, proj in enumerate(registry[-10:]):
            proj_table.add_row(
                str(i),
                proj.get("name", "?"),
                proj.get("framework", "?"),
                proj.get("genre", "?"),
                proj.get("path", "?")[:60],
            )
        console.print(proj_table)
